#!/bin/bash
set -e

# This script will automatically install and configure Logstash and Kibana

# Grab the fullpath of our root directory
ROOT=$(cd `dirname ${BASH_SOURCE[0]}` && echo $PWD)

#####
# Workaround for upstart not running while inside the Docker container
# @see https://github.com/dotcloud/docker/issues/1024
#####
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl

# We need the newest version of redis so we can use the batch function
apt-get install -y --force-yes python-software-properties unzip software-properties-common
add-apt-repository -y ppa:rwky/redis
apt-get update

apt-get install -y --force-yes redis-server openjdk-7-jre-headless rubygems nginx

# Redis serves as the queue for logstash logs
sed -ie 's#bind 127.0.0.1#bind 0.0.0.0#' /etc/redis/redis.conf
# This keeps redis background dumping from crashing if you run low
# on system memory.
echo "vm.overcommit_memory = 1" >> /etc/sysctl.conf
sysctl -p
service redis-server restart

# Install and configure elasticsearch
[ ! -f /tmp/elasticsearch.deb ] && curl -L https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.7.deb -o /tmp/elasticsearch.deb
dpkg -i /tmp/elasticsearch.deb
rm /tmp/elasticsearch.deb

# These configurations are for a large, 192GB Dell R720. You'll need to adjust
# them for use on any smaller systems.
#cp $ROOT/etc/elasticsearch/elasticsearch.yml .
#cp $ROOT/default/elasticsearch /etc/default/elasticsearch
/etc/init.d/elasticsearch start

# Logstash is just a jar and requires some additional configs
LOGHOME=/etc/logstash
mkdir $LOGHOME && pushd $LOGHOME
[ ! -f logstash.jar ] && curl -L https://logstash.objects.dreamhost.com/release/logstash-1.2.0-flatjar.jar -o logstash.jar
cp $ROOT/conf/indexer.conf $LOGHOME
cp $ROOT/init/logstash.conf /etc/init/
mkdir /var/lib/logstash # Required working directory for logstash
service logstash start
popd

# Install and configure the Kibana frontend
pushd /opt/
[ ! -f kibana-latest.zip ] && curl -LO http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip
unzip kibana-latest.zip
mv kibana-latest kibana
pushd kibana

# Copy over our nginx conf and restart
cp $ROOT/conf/nginx/kibana_nginx_conf /etc/nginx/sites-available/kibana
ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana
unlink /etc/nginx/sites-enabled/default
/etc/init.d/nginx restart

cat - <<FINISHED
Elasticsearch installation now complete. 

Services running:

  Logstash indexer
  Elasticsearch
  Redis
  nginx

nginx is serving Kibana on port 80

To start and stop logstash server:

  $ service logstash <start|stop|restart|status>

FINISHED
